name: Blank Issue
description: "Create an Issue"
labels: []
assignees: [ "carlosmiei", "frosty00" ]
body:
  - type: markdown
    attributes:
      value: |
        MUST READ THIS BEFORE SUBMITTING ISSUES (read the links, then delete this message before submitting):

        - https://github.com/ccxt/ccxt/wiki/FAQ
        - https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-submit-an-issue

        Make sure your local version of CCXT is up to date. Check by comparing the output of `ccxt.version` to https://github.com/ccxt/ccxt/blob/master/package.json#L3

        - OS:
        - Programming Language version:
        - CCXT version:

        \`\`\`
        REPLACE_THIS_WITH_YOUR_CODE_TO_REPRODUCE_THE_ISSUE_WITHOUT_YOUR_KEYS
        \`\`\`

  - type: textarea
    attributes:
      # invisible arabic question mark
      label: Øœ
